### ISSUE TITLE
Error: Unbound value String.lowercase_ascii makefile:15: recipe for target 'all' failed

### ISSUE THREAD

**Issue by gnsrivastava** [w-jaworski/AtomMap#1]
Trying to compile AtomMap using OCaml compiler version 4.02.3. It keeps giving me following error:

ocamlopt -o cr -I +xml-light -I +gsl -I +xlib -I +zip -I +bz2 -I /usr/local/lib/ocaml/4.02.3/ANSITerminal unix.cmxa xml-light.cmxa str.cmxa bigarray.cmxa nums.cmxa zip.cmxa bz2.cmxa xlib.cmxa  collection.mli collection.ml pair.mli pair.ml labels.mli labels.ml types.ml hash.mli hash.ml isomorphism.mli isomorphism.ml commonSubstructure.mli commonSubstructure.ml smiles.ml patterns.ml reactionClasses.ml atomMapping.ml import.ml molecule.ml matchingExec.ml matching_tests.ml
ocamlopt -o map_reaction -I +xml-light -I +gsl -I +xlib -I +zip -I +bz2 -I /usr/local/lib/ocaml/4.02.3/ANSITerminal unix.cmxa xml-light.cmxa str.cmxa bigarray.cmxa nums.cmxa zip.cmxa bz2.cmxa xlib.cmxa  collection.mli collection.ml pair.mli pair.ml labels.mli labels.ml types.ml hash.mli hash.ml isomorphism.mli isomorphism.ml commonSubstructure.mli commonSubstructure.ml smiles.ml patterns.ml reactionClasses.ml atomMapping.ml import.ml molecule.ml matchingExec.ml mapReaction.ml

File "smiles.ml", line 469, characters 33-55:
Error: Unbound value String.lowercase_ascii
makefile:15: recipe for target 'all' failed
make: *** [all] Error 2

I would appreciate any help. 

Thanks
Gopal

**Comment by w-jaworski** [comment]
OCaml version you have tried to compile AtomMap with is too old. 
According to OCaml manual (https://caml.inria.fr/pub/docs/manual-ocaml/libref/String.html)
Function String.lowercase_ascii was introduced in version 4.03.0 of  OCaml compiler.

Wojtek
