### ISSUE TITLE
String.lowercase

### ISSUE THREAD

**Issue by GlockPL** [w-jaworski/AtomMap#2]
Readme says to use OCaml version 4.02.3 but similar issue was raised and the author responded with using higher version of OCaml which causes banch of other issuses like problem with Xlist.
Solution is to chage two lines of code from
`String.lowercase_ascii`
to
`String.lowercase`
To allows to compile properly provided all other dependencies are also compiled with OCaml version 4.02.3

**Comment by w-jaworski** [comment]
Several month ago AtomMap was adapted to OCaml version 4.11.1. I have corrected README.md
